version: "3.9"
services:
  app:
    container_name: fastest-mirror-finder
    build: ./
    links:
        - redis
    ports:
        - "8080:8080"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
