# This workflow will run tests for fastestMirrorFinder module

name: FastestMirrorFinder Workflow

on: [push, pull_request]


jobs:
  CI:

    runs-on: ubuntu-latest

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./fastestMirrorFinder

    - name: Install dependencies
      working-directory: ./fastestMirrorFinder
      run: go mod download

    - name: Build
      working-directory: ./fastestMirrorFinder
      run: go build

    - name: Run go vet
      working-directory: ./fastestMirrorFinder
      run: go vet ./...

    - name: Run go fmt
      working-directory: ./fastestMirrorFinder
      run: go fmt ./...

    - name: Run test and Coverage
      working-directory: ./fastestMirrorFinder
      run: go test -v -covermode=count ./...
